// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsFqP9brE0UFos7KX7uZg0bw8L9GtRci8',
    appId: '1:689397435557:web:5cc57d9219a283dcfe514c',
    messagingSenderId: '689397435557',
    projectId: 'chat-dbestech',
    authDomain: 'chat-dbestech.firebaseapp.com',
    storageBucket: 'chat-dbestech.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv4PXWRVn_65iSPuFpMeKER5PLy_xCrWI',
    appId: '1:689397435557:android:34f92262fe49e398fe514c',
    messagingSenderId: '689397435557',
    projectId: 'chat-dbestech',
    storageBucket: 'chat-dbestech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoay5P3eujNhH4gwb6FIU3SirDV2FiU30',
    appId: '1:689397435557:ios:9b225726cdde5695fe514c',
    messagingSenderId: '689397435557',
    projectId: 'chat-dbestech',
    storageBucket: 'chat-dbestech.appspot.com',
    iosClientId: '689397435557-alv8omigh76pggji3e40taiqm224jtb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatDbestech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoay5P3eujNhH4gwb6FIU3SirDV2FiU30',
    appId: '1:689397435557:ios:9b225726cdde5695fe514c',
    messagingSenderId: '689397435557',
    projectId: 'chat-dbestech',
    storageBucket: 'chat-dbestech.appspot.com',
    iosClientId: '689397435557-alv8omigh76pggji3e40taiqm224jtb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatDbestech',
  );
}
